theme: jekyll-theme-time-machine
title: [The Absurdularity by Ted Suzan]
description: [Congratulations on buying your new Meat calculator!  It's almost time for the absurdularity, and it's almost time for the weekend! This is a philosophy book and user guide will make sure that you are as ready as you can be for what's coming.]
