theme: jekyll-theme-time-machine
title: [The Absurdularity by Ted Suzan]
description: [Congratulations on buying your new Meat calculator! You couldn't have chosen a better time. It's almost time for the absurdularity! This philosophy book and user guide will make sure that you are ready for it.]
